services:
    nopcommerce_web:
        build: .
        container_name: nopcommerce
        ports:
            - "5000:5000"
        depends_on:
            - nopcommerce_database
        networks:
            - nop-net
    nopcommerce_database:
        image: "mysql:9"
        container_name: nop-db
        environment:
            MYSQL_DATABASE: "nopdb"
            MYSQL_ROOT_PASSWORD: "nopnop"
            MYSQL_USER: "nop"
            MYSQL_PASSSWORD: "nop"
        volumes:
          - nopcommerce_data:/var/lib/mysql
        networks:
            - nop-net


volumes:
  nopcommerce_data: 

networks:
  nop-net: